"""Compare Q tables generated by different experiments"""
__author__ = 'Guilherme Varela'
__date__ = '2020-02-20'
import os
import numpy as np
import dill
# current project dependencies
from ilurl.envs.base import TrafficLightQLEnv



ROOT_DIR = os.environ['ILURL_HOME']
EMISSION_DIR = f"{ROOT_DIR}/data/emissions/"
# CONFIG_DIRS = ('4545', '5040', '5434', '6030')
CONFIG_DIRS = ('6030',)


filenames = ('intersection_20200220-2158131582235893.8645902.Q.1-85',
             'intersection_20200220-2159311582235971.1839051.Q.1-85',
             'intersection_20200220-2158221582235902.563563.Q.1-85',
             'intersection_20200220-2159181582235958.167368.Q.1-85',
             'intersection_20200220-2158061582235886.423499.Q.1-85',
             'intersection_20200220-2158081582235888.27206.Q.1-85')


import pdb
def qdist(Q, Q1):
    states = set(Q.keys()).union(set(Q1.keys()))
    distance = 0
    for state in states:
        actions = set(Q[state].keys()).union(set(Q1[state].keys()))
        dist, n = 0, 0
        for action in actions:
            dist = max(dist, np.abs(Q[state][action] - Q1[state][action]))
        distance = round(max(distance, dist), 1)
    return distance
 

if __name__ == '__main__':

    QS = []
    for config_dir in CONFIG_DIRS:
        for filename in filenames:
            path = f'{EMISSION_DIR}{config_dir}/{filename}.pickle'
            # env = TrafficLightQLEnv.load(path)
            with open(path, 'rb') as f:
                Q = dill.load(f)
            QS.append(Q)

    N = len(QS)
    D = np.zeros((N, N), dtype=np.float)
    for i in range(N - 1): 
        for j in range(i + 1, N):
            D[i, j] = qdist(QS[i], QS[j])

    print(D[:,1:])
